// https://www.mockaroo.com/
export const MOCK_CARS = [
	{
		id: 1,
		make: 'Ford',
		model: 'F250',
		year: 1984,
		color: 'Goldenrod',
	},
	{
		id: 2,
		make: 'Infiniti',
		model: 'IPL G',
		year: 2011,
		color: 'Indigo',
	},
	{
		id: 3,
		make: 'Maserati',
		model: 'Spyder',
		year: 1989,
		color: 'Pink',
	},
	{
		id: 4,
		make: 'Kia',
		model: 'Rio',
		year: 2012,
		color: 'Mauv',
	},
	{
		id: 5,
		make: 'Chevrolet',
		model: 'Suburban 2500',
		year: 2001,
		color: 'Puce',
	},
	{
		id: 6,
		make: 'GMC',
		model: 'Savana Cargo Van',
		year: 2006,
		color: 'Orange',
	},
	{
		id: 7,
		make: 'Suzuki',
		model: 'Grand Vitara',
		year: 1999,
		color: 'Blue',
	},
	{
		id: 8,
		make: 'Isuzu',
		model: 'Ascender',
		year: 2009,
		color: 'Khaki',
	},
	{
		id: 9,
		make: 'Hyundai',
		model: 'Sonata',
		year: 2011,
		color: 'Orange',
	},
	{
		id: 10,
		make: 'Toyota',
		model: 'Solara',
		year: 1999,
		color: 'Pink',
	},
	{
		id: 11,
		make: 'Subaru',
		model: 'SVX',
		year: 1993,
		color: 'Khaki',
	},
	{
		id: 12,
		make: 'Lexus',
		model: 'RX',
		year: 2003,
		color: 'Mauv',
	},
	{
		id: 13,
		make: 'Chevrolet',
		model: 'Camaro',
		year: 1967,
		color: 'Green',
	},
	{
		id: 14,
		make: 'Cadillac',
		model: 'Seville',
		year: 2004,
		color: 'Red',
	},
	{
		id: 15,
		make: 'Volkswagen',
		model: 'Cabriolet',
		year: 1992,
		color: 'Blue',
	},
	{
		id: 16,
		make: 'Spyker',
		model: 'C8 Laviolette',
		year: 2004,
		color: 'Aquamarine',
	},
	{
		id: 17,
		make: 'Kia',
		model: 'Optima',
		year: 2011,
		color: 'Puce',
	},
	{
		id: 18,
		make: 'Plymouth',
		model: 'Voyager',
		year: 2000,
		color: 'Fuscia',
	},
	{
		id: 19,
		make: 'Lexus',
		model: 'GX',
		year: 2004,
		color: 'Blue',
	},
	{
		id: 20,
		make: 'Mazda',
		model: 'RX-7',
		year: 1985,
		color: 'Pink',
	},
	{
		id: 21,
		make: 'Toyota',
		model: '4Runner',
		year: 1994,
		color: 'Green',
	},
	{
		id: 22,
		make: 'Mitsubishi',
		model: 'Galant',
		year: 1997,
		color: 'Crimson',
	},
	{
		id: 23,
		make: 'Suzuki',
		model: 'SJ',
		year: 1991,
		color: 'Goldenrod',
	},
	{
		id: 24,
		make: 'Land Rover',
		model: 'Range Rover',
		year: 2006,
		color: 'Fuscia',
	},
	{
		id: 25,
		make: 'Infiniti',
		model: 'QX',
		year: 2004,
		color: 'Orange',
	},
	{
		id: 26,
		make: 'Mercury',
		model: 'Topaz',
		year: 1984,
		color: 'Goldenrod',
	},
	{
		id: 27,
		make: 'Acura',
		model: 'RL',
		year: 1996,
		color: 'Orange',
	},
	{
		id: 28,
		make: 'Mitsubishi',
		model: 'Eclipse',
		year: 2005,
		color: 'Red',
	},
	{
		id: 29,
		make: 'Suzuki',
		model: 'Aerio',
		year: 2004,
		color: 'Yellow',
	},
	{
		id: 30,
		make: 'Lexus',
		model: 'LX',
		year: 2004,
		color: 'Green',
	},
	{
		id: 31,
		make: 'Morgan',
		model: 'Aero 8',
		year: 2009,
		color: 'Pink',
	},
	{
		id: 32,
		make: 'Isuzu',
		model: 'Axiom',
		year: 2004,
		color: 'Red',
	},
	{
		id: 33,
		make: 'Mercury',
		model: 'Capri',
		year: 1994,
		color: 'Maroon',
	},
	{
		id: 34,
		make: 'Chevrolet',
		model: 'Express 3500',
		year: 1997,
		color: 'Violet',
	},
	{
		id: 35,
		make: 'Mazda',
		model: 'MX-5',
		year: 1995,
		color: 'Red',
	},
	{
		id: 36,
		make: 'Mercedes-Benz',
		model: 'SL-Class',
		year: 2003,
		color: 'Pink',
	},
	{
		id: 37,
		make: 'Volvo',
		model: 'S60',
		year: 2007,
		color: 'Goldenrod',
	},
	{
		id: 38,
		make: 'Mitsubishi',
		model: 'Challenger',
		year: 2004,
		color: 'Yellow',
	},
	{
		id: 39,
		make: 'Chevrolet',
		model: 'Corsica',
		year: 1992,
		color: 'Green',
	},
	{
		id: 40,
		make: 'Mercedes-Benz',
		model: 'S-Class',
		year: 1998,
		color: 'Crimson',
	},
	{
		id: 41,
		make: 'Acura',
		model: 'RSX',
		year: 2006,
		color: 'Khaki',
	},
	{
		id: 42,
		make: 'BMW',
		model: '7 Series',
		year: 1994,
		color: 'Pink',
	},
	{
		id: 43,
		make: 'Ford',
		model: 'F150',
		year: 2012,
		color: 'Khaki',
	},
	{
		id: 44,
		make: 'Audi',
		model: '100',
		year: 1990,
		color: 'Maroon',
	},
	{
		id: 45,
		make: 'Suzuki',
		model: 'Aerio',
		year: 2003,
		color: 'Pink',
	},
	{
		id: 46,
		make: 'Subaru',
		model: 'SVX',
		year: 1992,
		color: 'Mauv',
	},
	{
		id: 47,
		make: 'Ford',
		model: 'Taurus X',
		year: 2008,
		color: 'Orange',
	},
	{
		id: 48,
		make: 'Plymouth',
		model: 'Grand Voyager',
		year: 1999,
		color: 'Puce',
	},
	{
		id: 49,
		make: 'Dodge',
		model: 'Viper',
		year: 1993,
		color: 'Crimson',
	},
	{
		id: 50,
		make: 'Audi',
		model: 'TT',
		year: 2002,
		color: 'Teal',
	},
];

export const MOCK_USERS = [
	{
		id: 1,
		firstName: 'Fredia',
		lastName: 'Sperwell',
		email: 'neco@neco.cz',
		createdAt: '5/11/2022',
	},
	{
		id: 2,
		firstName: 'Fredia',
		lastName: 'Spinley',
		email: 'neco@neco.cz',
		createdAt: '7/20/2022',
	},
	{
		id: 3,
		firstName: 'Fredia',
		lastName: 'Craxford',
		email: 'neco@neco.cz',
		createdAt: '12/21/2021',
	},
	{
		id: 4,
		firstName: 'Linus',
		lastName: 'Wheadon',
		email: 'lwheadon3@businessinsider.com',
		createdAt: '3/3/2022',
	},
	{
		id: 5,
		firstName: 'Dunstan',
		lastName: 'Morrott',
		email: 'dmorrott4@businessinsider.com',
		createdAt: '11/3/2021',
	},
	{
		id: 6,
		firstName: 'Estrellita',
		lastName: 'Alty',
		email: 'ealty5@answers.com',
		createdAt: '8/22/2022',
	},
	{
		id: 7,
		firstName: 'Win',
		lastName: 'Purselowe',
		email: 'wpurselowe6@nifty.com',
		createdAt: '8/14/2022',
	},
	{
		id: 8,
		firstName: 'Darcy',
		lastName: 'Test',
		email: 'dtest7@miitbeian.gov.cn',
		createdAt: '8/16/2022',
	},
	{
		id: 9,
		firstName: 'Jandy',
		lastName: 'Praill',
		email: 'jpraill8@1und1.de',
		createdAt: '4/3/2022',
	},
	{
		id: 10,
		firstName: 'Ellary',
		lastName: 'Dunckley',
		email: 'edunckley9@ycombinator.com',
		createdAt: '4/16/2022',
	},
	{
		id: 11,
		firstName: 'Ingrid',
		lastName: 'Tuberfield',
		email: 'ituberfielda@over-blog.com',
		createdAt: '3/1/2022',
	},
	{
		id: 12,
		firstName: 'Rayshell',
		lastName: 'Drinkhill',
		email: 'rdrinkhillb@miibeian.gov.cn',
		createdAt: '12/6/2021',
	},
	{
		id: 13,
		firstName: 'Simmonds',
		lastName: 'Belle',
		email: 'sbellec@cafepress.com',
		createdAt: '12/28/2021',
	},
	{
		id: 14,
		firstName: 'Welsh',
		lastName: 'How to preserve',
		email: 'whowtopreserved@npr.org',
		createdAt: '9/20/2021',
	},
	{
		id: 15,
		firstName: 'Tonye',
		lastName: "O'Hederscoll",
		email: 'tohederscolle@stanford.edu',
		createdAt: '9/26/2021',
	},
	{
		id: 16,
		firstName: 'Lancelot',
		lastName: 'Kevlin',
		email: 'lkevlinf@spotify.com',
		createdAt: '2/7/2022',
	},
	{
		id: 17,
		firstName: 'Teodor',
		lastName: 'Turnell',
		email: 'tturnellg@mlb.com',
		createdAt: '4/9/2022',
	},
	{
		id: 18,
		firstName: 'Percy',
		lastName: 'Geraldini',
		email: 'pgeraldinih@creativecommons.org',
		createdAt: '9/16/2022',
	},
	{
		id: 19,
		firstName: 'Cortney',
		lastName: 'Hugonin',
		email: 'chugonini@deviantart.com',
		createdAt: '3/4/2022',
	},
	{
		id: 20,
		firstName: 'Sonny',
		lastName: 'Krimmer',
		email: 'skrimmerj@360.cn',
		createdAt: '4/22/2022',
	},
	{
		id: 21,
		firstName: 'Sofie',
		lastName: 'Daniau',
		email: 'sdaniauk@bigcartel.com',
		createdAt: '8/25/2022',
	},
	{
		id: 22,
		firstName: 'Augusto',
		lastName: 'Sievewright',
		email: 'asievewrightl@omniture.com',
		createdAt: '1/23/2022',
	},
	{
		id: 23,
		firstName: 'Wolfy',
		lastName: 'Feaviour',
		email: 'wfeaviourm@webs.com',
		createdAt: '5/16/2022',
	},
	{
		id: 24,
		firstName: 'Javier',
		lastName: 'Dorkins',
		email: 'jdorkinsn@apple.com',
		createdAt: '4/25/2022',
	},
	{
		id: 25,
		firstName: 'Sherrie',
		lastName: 'Stebbings',
		email: 'sstebbingso@last.fm',
		createdAt: '3/21/2022',
	},
	{
		id: 26,
		firstName: 'Jan',
		lastName: 'Roumier',
		email: 'jroumierp@umn.edu',
		createdAt: '8/1/2022',
	},
	{
		id: 27,
		firstName: 'Francois',
		lastName: 'Croad',
		email: 'fcroadq@livejournal.com',
		createdAt: '2/21/2022',
	},
	{
		id: 28,
		firstName: 'Sharyl',
		lastName: 'Tippin',
		email: 'stippinr@naver.com',
		createdAt: '7/27/2022',
	},
	{
		id: 29,
		firstName: 'Dee dee',
		lastName: 'Biaggiotti',
		email: 'dbiaggiottis@sogou.com',
		createdAt: '11/6/2021',
	},
	{
		id: 30,
		firstName: 'Brucie',
		lastName: 'Blockley',
		email: 'bblockleyt@yellowpages.com',
		createdAt: '10/19/2021',
	},
	{
		id: 31,
		firstName: 'Annice',
		lastName: 'Brownlea',
		email: 'abrownleau@about.me',
		createdAt: '3/10/2022',
	},
	{
		id: 32,
		firstName: 'Romola',
		lastName: 'Quare',
		email: 'rquarev@umn.edu',
		createdAt: '8/29/2022',
	},
	{
		id: 33,
		firstName: 'Kaylyn',
		lastName: 'Iannitti',
		email: 'kiannittiw@google.pl',
		createdAt: '8/2/2022',
	},
	{
		id: 34,
		firstName: 'Bayard',
		lastName: 'Learmount',
		email: 'blearmountx@google.com',
		createdAt: '1/16/2022',
	},
	{
		id: 35,
		firstName: 'Gayel',
		lastName: 'Pennone',
		email: 'gpennoney@paginegialle.it',
		createdAt: '2/27/2022',
	},
	{
		id: 36,
		firstName: 'Jacquelin',
		lastName: 'Purveys',
		email: 'jpurveysz@google.it',
		createdAt: '10/4/2021',
	},
	{
		id: 37,
		firstName: 'Shane',
		lastName: 'Pudge',
		email: 'spudge10@imageshack.us',
		createdAt: '8/12/2022',
	},
	{
		id: 38,
		firstName: 'Garnet',
		lastName: 'Cookman',
		email: 'gcookman11@springer.com',
		createdAt: '1/20/2022',
	},
	{
		id: 39,
		firstName: 'Babbette',
		lastName: 'Paszek',
		email: 'bpaszek12@ebay.co.uk',
		createdAt: '9/12/2022',
	},
	{
		id: 40,
		firstName: 'Ludvig',
		lastName: 'Chellenham',
		email: 'lchellenham13@nytimes.com',
		createdAt: '3/13/2022',
	},
	{
		id: 41,
		firstName: 'Leoine',
		lastName: 'Tingey',
		email: 'ltingey14@instagram.com',
		createdAt: '9/8/2022',
	},
	{
		id: 42,
		firstName: 'Burr',
		lastName: 'Matteacci',
		email: 'bmatteacci15@storify.com',
		createdAt: '11/24/2021',
	},
	{
		id: 43,
		firstName: 'Glenden',
		lastName: 'Likly',
		email: 'glikly16@blogger.com',
		createdAt: '12/29/2021',
	},
	{
		id: 44,
		firstName: 'Ludovico',
		lastName: 'Gutherson',
		email: 'lgutherson17@edublogs.org',
		createdAt: '10/31/2021',
	},
	{
		id: 45,
		firstName: 'Ginny',
		lastName: 'Le Sarr',
		email: 'glesarr18@delicious.com',
		createdAt: '7/16/2022',
	},
	{
		id: 46,
		firstName: 'Ernestine',
		lastName: 'Whetson',
		email: 'ewhetson19@w3.org',
		createdAt: '1/10/2022',
	},
	{
		id: 47,
		firstName: 'Bruis',
		lastName: 'Tratton',
		email: 'btratton1a@artisteer.com',
		createdAt: '6/8/2022',
	},
	{
		id: 48,
		firstName: 'Standford',
		lastName: 'Enston',
		email: 'senston1b@dmoz.org',
		createdAt: '3/3/2022',
	},
	{
		id: 49,
		firstName: 'Wood',
		lastName: 'Brabin',
		email: 'wbrabin1c@accuweather.com',
		createdAt: '12/14/2021',
	},
	{
		id: 50,
		firstName: 'Haleigh',
		lastName: 'Lockwood',
		email: 'hlockwood1d@europa.eu',
		createdAt: '10/17/2021',
	},
];
