name: test

on:

  push:
    branches: [ "testpublish" ]

  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: yarn

      - name: publish
        run: yarn publish patch
